version: "3.8"

services:
  db:
    container_name: postgres_db
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mynewdb
    volumes:
      - db_data:/var/lib/postgresql/data
  
  supabase-storage:
    container_name: supabase_storage
    image: bitnami/supabase-storage:latest
    restart: always
    volumes:
      - ./data:/bitnami
    environment:
      - NEXT_PUBLIC_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlbHlob3l5d2xmenBrbWVvZnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODQyNTY5MjIsImV4cCI6MTk5OTgzMjkyMn0.P-gzhTGmL-0aRI_cS4S0PVQ7sfryltaU2meK6F_J7C0'
      - NEXT_PUBLIC_SUPABASE_URL = 'https://eelyhoyywlfzpkmeofum.supabase.co'
      - SUPABASE_SERVICE_ROLE_KEY=YOUR_SERVICE_ROLE_KEY
      - SUPABASE_JWT_SECRET=YOUR_JWT_SECRET


volumes:
  db_data: