version: "3.8"

services:
  db:
    container_name: postgres_db
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mynewdb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
