name: hesp deployment

on:
  push:
    branches:
      - test-end-to-end

jobs:
  vercel_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: end to end test
        run: yarn ;cd apps; cd hesp; export VERCEL_PREVIEW_OUTPUT=https://google.com ;yarn e2e-test
