name: Test migration and seeding

on:
  pull_request:
    branches:
      - main

jobs:
  test_migration_and_seed:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Prisma CLI
        run: npm i -g prisma

      - name: Set up test database
        run: |
          sudo apt-get -yqq install libpq-dev
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db" > apps/hesp/.env

      - name: Install dependencies
        working-directory: apps/hesp
        run: npm install

      - name: Build the project
        working-directory: apps/hesp
        run: npm run build

      - name: Run migrations
        working-directory: apps/hesp
        run: |
          prisma migrate deploy

      - name: Seed test database
        working-directory: apps/hesp
        run: |
          npx ts-node prisma/seed.ts
