name: hesp deployment

on:
  pull_request:
    branches:
      - main

jobs:


  run_e2e_tests_locally:
    needs: test_migration_and_seed
    runs-on: ubuntu-latest

    env: 
      SEED_DATA_FILE: prisma/seed.ts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Prisma CLI
        run: npm i -g prisma

      - name: Set up test database
        run: |
          sudo apt-get -yqq install libpq-dev
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > apps/hesp/.env

      - name: Install dependencies
        working-directory: apps/hesp
        run: npm install

      - name: Build the project
        working-directory: apps/hesp
        run: npm run build

      - name: Run migrations
        working-directory: apps/hesp
        run: |
          prisma migrate deploy

      - name: Seed test database
        working-directory: apps/hesp
        run: |
          npx ts-node "${SEED_DATA_FILE}"

      - name: Run e2e tests
        working-directory: apps/hesp
        run: |
          yarn e2e-test-local
